export const shifts = [
  { label: "Shift A (7am-3:30pm)", value: "A" },
  { label: "Shift B (3pm-11:30pm)", value: "B" },
  { label: "Shift C (11pm-7:30am)", value: "C" },
];

export const employees = [
  { id: 1, name: "Lavkush Singh", dept: "IT", manager: "Amit Sharma", shift: "A", status: "Active", role: "Employee" },
  { id: 2, name: "Priya Mehra", dept: "HR", manager: "Manoj Gupta", shift: "B", status: "Active", role: "Employee" },
  { id: 3, name: "Rohit Verma", dept: "Finance", manager: "Sunita Rani", shift: "C", status: "Active", role: "Employee" },
  { id: 4, name: "Amit Sharma", dept: "IT", manager: "Sunil Kumar", shift: "A", status: "Active", role: "Manager" },
  { id: 5, name: "Deepika Singh", dept: "Operations", manager: "Vikas Joshi", shift: "B", status: "Active", role: "Employee" },
  { id: 6, name: "Sunil Kumar", dept: "Admin", manager: "Rajesh Tiwari", shift: "C", status: "Active", role: "Admin" },
  { id: 7, name: "Vikas Joshi", dept: "Operations", manager: "Sunil Kumar", shift: "A", status: "Active", role: "Manager" },
  { id: 8, name: "Sunita Rani", dept: "Finance", manager: "Rajesh Tiwari", shift: "B", status: "Active", role: "Manager" },
  { id: 9, name: "Anjali Patel", dept: "Marketing", manager: "Amit Sharma", shift: "C", status: "Active", role: "Employee" },
  { id: 10, name: "Rajesh Tiwari", dept: "Admin", manager: "None", shift: "A", status: "Active", role: "Admin" },
  { id: 11, name: "Harsh Vardhan", dept: "IT", manager: "Amit Sharma", shift: "B", status: "Active", role: "Employee" },
  { id: 12, name: "Meena Kumari", dept: "HR", manager: "Manoj Gupta", shift: "C", status: "Active", role: "Employee" },
  { id: 13, name: "Nikhil Jain", dept: "Finance", manager: "Sunita Rani", shift: "A", status: "Active", role: "Employee" },
  { id: 14, name: "Rakesh Yadav", dept: "IT", manager: "Amit Sharma", shift: "B", status: "Active", role: "Employee" },
  { id: 15, name: "Shweta Sinha", dept: "Operations", manager: "Vikas Joshi", shift: "C", status: "Active", role: "Employee" },
  { id: 16, name: "Tarun Das", dept: "Admin", manager: "Rajesh Tiwari", shift: "A", status: "Active", role: "Employee" },
  { id: 17, name: "Manoj Gupta", dept: "HR", manager: "Sunil Kumar", shift: "B", status: "Active", role: "Manager" },
  { id: 18, name: "Kavita Mishra", dept: "Finance", manager: "Sunita Rani", shift: "C", status: "Active", role: "Employee" },
  { id: 19, name: "Pawan Singh", dept: "Marketing", manager: "Amit Sharma", shift: "A", status: "Active", role: "Employee" },
  { id: 20, name: "Divya Bharti", dept: "Operations", manager: "Vikas Joshi", shift: "B", status: "Active", role: "Employee" },
  { id: 21, name: "Ajay Kumar", dept: "IT", manager: "Amit Sharma", shift: "C", status: "Active", role: "Employee" },
  { id: 22, name: "Neha Agarwal", dept: "HR", manager: "Manoj Gupta", shift: "A", status: "Active", role: "Employee" },
  { id: 23, name: "Sourabh Sen", dept: "Finance", manager: "Sunita Rani", shift: "B", status: "Active", role: "Employee" },
  { id: 24, name: "Chirag Sharma", dept: "Operations", manager: "Vikas Joshi", shift: "C", status: "Active", role: "Employee" },
  { id: 25, name: "Sneha Jain", dept: "Marketing", manager: "Amit Sharma", shift: "A", status: "Active", role: "Employee" },
  { id: 26, name: "Prakash Mehta", dept: "Admin", manager: "Rajesh Tiwari", shift: "B", status: "Active", role: "Employee" },
  { id: 27, name: "Jyoti Rawat", dept: "HR", manager: "Manoj Gupta", shift: "C", status: "Active", role: "Employee" },
  { id: 28, name: "Sagar Saxena", dept: "IT", manager: "Amit Sharma", shift: "A", status: "Active", role: "Employee" },
  { id: 29, name: "Rahul Dubey", dept: "Finance", manager: "Sunita Rani", shift: "B", status: "Active", role: "Employee" },
  { id: 30, name: "Ritu Pathak", dept: "Operations", manager: "Vikas Joshi", shift: "C", status: "Active", role: "Employee" },
  { id: 31, name: "Vivek Chauhan", dept: "Marketing", manager: "Amit Sharma", shift: "A", status: "Active", role: "Employee" },
  { id: 32, name: "Rashmi Sharma", dept: "Admin", manager: "Rajesh Tiwari", shift: "B", status: "Active", role: "Employee" },
  { id: 33, name: "Arun Singh", dept: "IT", manager: "Amit Sharma", shift: "C", status: "Active", role: "Employee" },
  { id: 34, name: "Sheetal Pandey", dept: "HR", manager: "Manoj Gupta", shift: "A", status: "Active", role: "Employee" },
  { id: 35, name: "Vimal Dubey", dept: "Finance", manager: "Sunita Rani", shift: "B", status: "Active", role: "Employee" },
  { id: 36, name: "Ayesha Khan", dept: "Operations", manager: "Vikas Joshi", shift: "C", status: "Active", role: "Employee" },
  { id: 37, name: "Sandeep Choudhary", dept: "Marketing", manager: "Amit Sharma", shift: "A", status: "Active", role: "Employee" },
  { id: 38, name: "Bharat Kumar", dept: "Admin", manager: "Rajesh Tiwari", shift: "B", status: "Active", role: "Employee" },
  { id: 39, name: "Ekta Verma", dept: "HR", manager: "Manoj Gupta", shift: "C", status: "Active", role: "Employee" },
  { id: 40, name: "Sachin Yadav", dept: "IT", manager: "Amit Sharma", shift: "A", status: "Active", role: "Employee" },
  { id: 41, name: "Sudhir Mishra", dept: "Finance", manager: "Sunita Rani", shift: "B", status: "Active", role: "Employee" },
  { id: 42, name: "Preeti Rani", dept: "Operations", manager: "Vikas Joshi", shift: "C", status: "Active", role: "Employee" },
  { id: 43, name: "Sushil Singh", dept: "Marketing", manager: "Amit Sharma", shift: "A", status: "Active", role: "Employee" },
  { id: 44, name: "Megha Aggarwal", dept: "Admin", manager: "Rajesh Tiwari", shift: "B", status: "Active", role: "Employee" },
  { id: 45, name: "Arvind Jain", dept: "IT", manager: "Amit Sharma", shift: "C", status: "Active", role: "Employee" },
  { id: 46, name: "Manisha Yadav", dept: "HR", manager: "Manoj Gupta", shift: "A", status: "Active", role: "Employee" },
  { id: 47, name: "Shashank Gupta", dept: "Finance", manager: "Sunita Rani", shift: "B", status: "Active", role: "Employee" },
  { id: 48, name: "Vinod Pandey", dept: "Operations", manager: "Vikas Joshi", shift: "C", status: "Active", role: "Employee" },
  { id: 49, name: "Tanuja Roy", dept: "Marketing", manager: "Amit Sharma", shift: "A", status: "Active", role: "Employee" },
  { id: 50, name: "Pallavi Sharma", dept: "Admin", manager: "Rajesh Tiwari", shift: "B", status: "Active", role: "Employee" }
];


export const admins = [
  { id: 101, name: "Amit Sharma", dept: "IT", role: "Admin" },
  { id: 102, name: "Priya Kumar", dept: "HR", role: "Admin" },
  { id: 103, name: "Nilesh Mehta", dept: "Finance", role: "Admin" }
];
